on: [push]

jobs:
  deploy_to_clouds:
    runs-on: self-hosted
    name: Portal Deploy
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Delete Document Objects
      run: |
        http http://localhost:8001/document_objects Kong-Admin-Token:KongRul3z! | jq -c '.data[].id' | while read id; do;    echo "Deleting the document_object with the ID: ${id}";    http --ignore-stdin DELETE http://localhost:8001/document_objects/$id Kong-Admin-Token:KongRul3z!;done
      - name: Kong Deploy Order API
      uses: ./.github/actions/portal-deploy-action
      with:
        kong-config-type: kong-declarative-config
        external-service: pizza-order-service
        external-service-host: mockbin.org
        openapi-spec: orders.yaml
    - name: Deploy Dev Portal
      run: |
        portal deploy default
