on: [push]

jobs:
  deploy_to_clouds:
    runs-on: self-hosted
    name: Deploy OpenAPI to Kong Gateway and Dev Portal
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Delete Document Objects and Applications
      run:  sh ./bin/delete_document_objects.sh
    - name: Deploy OpenAPI spec to Kong's GW via DecK
      uses: ./.github/actions/portal-deploy-action
      with:
        kong-config-type: kong-declarative-config
        external-service: pizza-order-service
        external-service-host: mockbin.org
        openapi-spec: orders.yaml
    - name: Deploy OpenAPI spec to Kong's Dev Portal
      run: |
        portal deploy default
